[workspace]

members = [
    "demo",
    "crates/vertigo-browserdriver",
    "crates/vertigo",
    "crates/vertigo-html",
    "crates/vertigo-html-macro",
    "crates/vertigo-testing",
    "crates/vertigo-typescript-makro",
]


[profile.release]
lto = true

#for speed
opt-level = 's'

#for size
#opt-level = 'z'
