[workspace]

members = [
    "app",
    "crates/browserdriver",
    "crates/vertigo",
    "crates/vertigo-html",
    "crates/vertigo-html-macro",
]


[profile.release]
lto = true

#for speed
opt-level = 's'

#for size
#opt-level = 'z'
