[package]
name = "vertigo-typescript-macro"
version = "0.1.0-alpha.3"
authors = ["Michał Pokrywka <wolfmoon@o2.pl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Html2Vertigo conversion macro"

[lib]
name = "vertigo_html_macro"
proc-macro = true

[dependencies]
log = "0.4.14"
proc-macro2 = "1.0.24"
proc-macro-error = "1.0.4"

